//HintName: MyCommand.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MyCommand"/>" and creating a new MyCommand instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class MyCommand : CommandClass
    {

        public MyCommand()
        {
        }

        [SetsRequiredMembers()]
        protected MyCommand(DataValue<string> nameDataValue)
            : this()
        {
            if (ValueIsAvailable(nameDataValue)) Name = nameDataValue.Value;

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                // This is generated because it should not be used outside the constructor.
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        static partial void RegisterCustomDefaults(Builder<MyNamespace.MyCommand> builder, DefaultDataProvider<MyNamespace.MyCommand> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class MyCommandDataDefinition : CommandDataDefinition<MyNamespace.MyCommand, MyNamespace.MyCommand>
        {
            public static MyNamespace.MyCommand.MyCommandDataDefinition Instance = new(null, MyNamespace.MyCommand.MyCommandDataDefinition.Instance);

            public MyCommandDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new MyCommandDataValues();
                Name = new OptionDataDefinition<string>(this, nameof(Name))
                {
                    DataType = typeof(string), 
                    IsRequired = true, 
                };

                Add(new MorningGreetingCommand.MorningGreetingCommandDataDefinition(this, this.RootDataDefinition)
                {
                });

                Add(new EveningGreetingCommand.EveningGreetingCommandDataDefinition(this, this.RootDataDefinition)
                {
                });

                RegisterCustomizations();
            }
            public OptionDataDefinition<string> Name { get; }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                    nameof(Name) => Name,
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[1];
                retValues[0] = operationContainer.Operate(Name);
                return retValues;
            }

        }

        public class MyCommandDataValues : DataValues<MyNamespace.MyCommand>
        {
            public static MyNamespace.MyCommand.MyCommandDataDefinition CommandDataDefinition = new(null, MyNamespace.MyCommand.MyCommandDataDefinition.Instance);
            private Type commandClassType = typeof(MyCommand);

            public MyCommandDataValues()
                : base()
            {
                Name = DataValue<string>.Create(nameof(Name), commandClassType, this, CommandDataDefinition.Name);
                Add(Name);
            }

            public override bool Operate<TReturn>(IOperateOnDataValue<MyNamespace.MyCommand, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            public DataValue<string> Name { get; }

            protected override MyCommand CreateInstance()
            {
                return new MyCommand(Name);            }
        }
    }
}
