//HintName: EveningGreetingCommand.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="EveningGreetingCommand"/>" and creating a new EveningGreetingCommand instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class EveningGreetingCommand : MyCommand
    {

        public EveningGreetingCommand()
        {
        }

        [SetsRequiredMembers()]
        protected EveningGreetingCommand(DataValue<int> ageDataValue, DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
            if (ValueIsAvailable(ageDataValue)) Age = ageDataValue.Value;

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                // This is generated because it should not be used outside the constructor.
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        static partial void RegisterCustomDefaults(Builder<MyNamespace.MyCommand> builder, DefaultDataProvider<MyNamespace.MyCommand> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class EveningGreetingCommandDataDefinition : CommandDataDefinition<MyNamespace.MyCommand>
        {

            public EveningGreetingCommandDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new EveningGreetingCommandDataValues(this);
                Age = new OptionDataDefinition<int>(this, nameof(Age))
                {
                    DataType = typeof(int), 
                    IsRequired = false, 
                };

                Add(new Bar.BarDataDefinition(this, this.RootDataDefinition)
                {
                });

                RegisterCustomizations();
            }
            public OptionDataDefinition<int> Age { get; }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                    nameof(Age) => Age,
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[1];
                retValues[0] = operationContainer.Operate(Age);
                return retValues;
            }

        }

        public class EveningGreetingCommandDataValues : DataValues<MyNamespace.MyCommand>
        {

            public EveningGreetingCommandDataValues(EveningGreetingCommandDataDefinition commandDefinition)
                : base(commandDefinition)
            {
                Age = DataValue<int>.Create(nameof(Age), commandClassType, this, commandDefinition.Age);
                Add(Age);
            }

             public override bool Operate<TReturn>(IOperateOnDataValue<MyNamespace.MyCommand, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Age, operationContainer, out var _);
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            private Type commandClassType = typeof(EveningGreetingCommand);
            public DataValue<int> Age { get; }
            public DataValue<string> Name { get; }

            protected override EveningGreetingCommand CreateInstance()
            {
                return new EveningGreetingCommand(Age, Name);            }
        }
    }
}
