//HintName: Bar.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="Bar"/>" and creating a new Bar instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class Bar : EveningGreetingArgs
    {

        [SetsRequiredMembers()]
        protected Bar(DataValue<int> ageDataValue, DataValue<string> nameDataValue)
            : base(ageDataValue, nameDataValue)
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyNamespace.MyArgs> builder, DefaultDataProvider<MyNamespace.MyArgs> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class BarDataDefinition : CommandDataDefinition<MyNamespace.MyArgs>
        {

            public BarDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new BarDataValues(this);
                RegisterCustomizations();
            }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[0];
                return retValues;
            }

        }

        public class BarDataValues : DataValues<MyNamespace.MyArgs>
        {

            public BarDataValues(BarDataDefinition commandDefinition)
                : base(commandDefinition)
            {
            }

             public override bool Operate<TReturn>(IOperateOnDataValue<MyNamespace.MyArgs, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Age, operationContainer, out var _);
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            private Type argsType = typeof(Bar);
            public DataValue<int> Age { get; }
            public DataValue<string> Name { get; }

            protected override Bar CreateInstance()
            {
                return new Bar(Age, Name);            }
        }
    }
}
