//HintName: Cli.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using MyNamespace;

/// <summary>
/// Auto-generated partial class that supplies the root ArgsBuilder type.
/// </summary>
public class Cli
{
    /// <summary>
    /// Creates a Builder, which can be configured, the System.CommandLine API can be accessed, and which can be reused (especially helpful in testing). 
    /// </summary>
    /// <remarks>
    /// The args class specified as the type argument must be public.
    /// </remarks>
    /// <remarks>
    /// You may need to build after editing this line.
    /// </remarks>
    /// <remarks>
    /// It is not currently clear how builders and configuration are the same and different and thus expected changes in this space. Accessing it is currently difficult to avoid confusion.
    /// </remarks>
    /// <typeparam name="TRootCommand">The type containing the CLI definition, the root command if there are subcommands.</typeparam>

    public static Builder<TRootCommand>? CreateBuilder<TRootCommand>()
    {
        if (typeof(TRootCommand) == typeof(MyCommand))
        {
            var builder = new Builder<MyCommand>(new MyCommand.MyCommandDataDefinition(null, null));
            return builder is Builder<TRootCommand> typedBuilder
                  ? typedBuilder
                  : throw new InvalidOperationException("Type mismatch creating builder.");
        }
        return null;
    }

    /// <summary>
    /// Parses CLI arguments to fill the specified args type.<br/>This method is generated specific to the type argument.<br/>You may need to build after editing.
    /// </summary>
    /// <remarks>
    /// The args class specified as the type argument must be public.
    /// </remarks>
    /// <typeparam name="TRootCommand">The type containing the CLI definition.</typeparam>
    /// <param name="args">Optionaly pass the commandline args, using the keyword `args`. If not passed, they will be retrieved for you.</param>

    public static Result<TRootCommand> ParseAxgs<TRootCommand>(string[]? args = null)
    {
        var builder = CreateBuilder<TRootCommand>();
        if (builder is null)
        {
            var result = new Result<TRootCommand>(Builder<TRootCommand>.GetArgsFromEnvironment());
            result.AddDiagnostic(new Diagnostic(DiagnosticId.CouldNotFindBuilder.ToValidationIdString(), DiagnosticSeverity.Error));
            return result;
        }
        return builder.ParseAxgs(args);
    }

    /// <summary>
    /// Attempts to parses CLI arguments and fill the specified args type.<br/>This method is generated specific to the type argument.<br/>You may need to build after editing.
    /// </summary>
    /// <remarks>
    /// The args class specified as the type argument must be public.
    /// </remarks>
    /// <typeparam name="TRootCommand">The type containing the CLI definition.</typeparam>
    /// <param name="result">An out parameter that contains an instance of the requested class and supporting data, such as diagnostics, a suggested CLI return value, etc.</param>
    /// <param name="args">Optionaly pass the commandline args, using the keyword `args`. If not passed, they will be retrieved for you.</param>
    /// <exception cref="InvalidOperationException">To be implemented soon.</param>

    public static bool TryParseAxgs<TRootCommand>(out Result<TRootCommand> result, string[]? args = null)
    {
        result = ParseAxgs<TRootCommand>(args);
        return result.IsValid;
    }
}
