//HintName: EveningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="EveningGreetingArgs"/>" and creating a new EveningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class EveningGreetingArgs : MyArgs
    {

        public EveningGreetingArgs()
        {
        }

        [SetsRequiredMembers()]
        protected EveningGreetingArgs(DataValue<int> ageDataValue, DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
            if (ValueIsAvailable(ageDataValue)) Age = ageDataValue.Value;

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                // This is generated because it should not be used outside the constructor.
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        static partial void RegisterCustomDefaults(Builder<MyNamespace.MyArgs> builder, DefaultDataProvider<MyNamespace.MyArgs> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class EveningGreetingArgsDataDefinition : CommandDataDefinition<MyNamespace.MyArgs>
        {

            public EveningGreetingArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new EveningGreetingArgsDataValues(this);
                Age = new OptionDataDefinition<int>(this, nameof(Age))
                {
                    DataType = typeof(int), 
                    IsRequired = false, 
                };

                Add(new Bar.BarDataDefinition(this, this.RootDataDefinition)
                {
                });

                RegisterCustomizations();
            }
            public OptionDataDefinition<int> Age { get; }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                    nameof(Age) => Age,
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[1];
                retValues[0] = operationContainer.Operate(Age);
                return retValues;
            }

        }

        public class EveningGreetingArgsDataValues : DataValues<MyNamespace.MyArgs>
        {

            public EveningGreetingArgsDataValues(EveningGreetingArgsDataDefinition commandDefinition)
                : base(commandDefinition)
            {
                Age = DataValue<int>.Create(nameof(Age), argsType, this, commandDefinition.Age);
                Add(Age);
            }

             public override bool Operate<TReturn>(IOperateOnDataValue<MyNamespace.MyArgs, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Age, operationContainer, out var _);
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            private Type argsType = typeof(EveningGreetingArgs);
            public DataValue<int> Age { get; }
            public DataValue<string> Name { get; }

            protected override EveningGreetingArgs CreateInstance()
            {
                return new EveningGreetingArgs(Age, Name);            }
        }
    }
}
