//HintName: MorningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MorningGreetingArgs" />
    /// and creating a new MorningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class MorningGreetingArgs : MyArgs, IArgs<MyArgs>
    {

        [SetsRequiredMembers()]

        private MorningGreetingArgs(DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
        }

        public override IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
        {
            return new MorningGreetingArgs.MorningGreetingArgsArgsBuilder();
        }

        /// <summary>
        /// </summary>
        internal class MorningGreetingArgsArgsBuilder : ArgsBuilder<MyArgs>
        {
            public ArgsBuilder<MyArgs>? ActiveArgsBuilder { get; set; }

            public override void Initialize(Builder<MyArgs> builder)
            {
                var cliDataProvider = GetCliDataProvider(builder);
                var rootCommand = new System.CommandLine.Command("MyArgs")
                {
                    Description = null,
                };

                rootCommand.SetAction(p => { ActiveArgsBuilder = this; return 0; });
                cliDataProvider.RootCommand = rootCommand;
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(Builder<MyArgs> builder)
            {
                var validationFailures = new List<ValidationFailure?>();
                return validationFailures
           .Where(x => x is not null)
           .Select(x => x!);
            }

            protected override MyArgs CreateInstance(Builder<MyArgs> builder)
            {
                var nameDataValue = builder.GetDataValue<string>("Name");

                var newArgs = new MyArgs(nameDataValue);
                return newArgs;
            }
        }
    }
}
