//HintName: MorningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MorningGreetingArgs"/>" and creating a new MorningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class MorningGreetingArgs : MyArgs
    {

        [SetsRequiredMembers()]
        protected MorningGreetingArgs(DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class MorningGreetingArgsDataDefinition : CommandDataDefinition<MyArgs>
        {

            public MorningGreetingArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new MorningGreetingArgsDataValues(this);
                RegisterCustomizations();
            }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[0];
                return retValues;
            }

        }

        public class MorningGreetingArgsDataValues : DataValues<MyArgs>
        {

            public MorningGreetingArgsDataValues(MorningGreetingArgsDataDefinition commandDefinition)
                : base(commandDefinition)
            {
            }

             public override bool Operate<TReturn>(IOperateOnDataValue<MyArgs, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            private Type argsType = typeof(MorningGreetingArgs);
            public DataValue<string> Name { get; }

            protected override MorningGreetingArgs CreateInstance()
            {
                return new MorningGreetingArgs(Name);            }
        }
    }
}
