//HintName: MorningGreetingCommand.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MorningGreetingCommand"/>" and creating a new MorningGreetingCommand instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    partial class MorningGreetingCommand : MyCommand
    {

        [SetsRequiredMembers()]
        protected MorningGreetingCommand(DataValue<string> nameDataValue)
            : base(nameDataValue)
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyNamespace.MyCommand> builder, DefaultDataProvider<MyNamespace.MyCommand> defaultDataProvider);

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class MorningGreetingCommandDataDefinition : CommandDataDefinition<MyNamespace.MorningGreetingCommand, MyNamespace.MyCommand>
        {
            public static MyNamespace.MorningGreetingCommand.MorningGreetingCommandDataDefinition Instance = new(MyNamespace.MyCommand.MyCommandDataDefinition.Instance, MyNamespace.MyCommand.MyCommandDataDefinition.Instance);

            public MorningGreetingCommandDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new MorningGreetingCommandDataValues();
                RegisterCustomizations();
            }

            protected override MemberDataDefinition? GetMemberDefinition(string memberName)
            {
                return memberName switch
                {
                };
            }

            public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
            {
                var retValues = new TReturn[0];
                return retValues;
            }

        }

        public class MorningGreetingCommandDataValues : MyNamespace.MyCommand.MyCommandDataValues
        {
            public static MyNamespace.MorningGreetingCommand.MorningGreetingCommandDataDefinition CommandDataDefinition = new(MyNamespace.MyCommand.MyCommandDataDefinition.Instance, MyNamespace.MyCommand.MyCommandDataDefinition.Instance);
            private Type commandClassType = typeof(MorningGreetingCommand);

            public MorningGreetingCommandDataValues()
                : base()
            {
            }

            public override bool Operate<TReturn>(IOperateOnDataValue<MyNamespace.MyCommand, TReturn> operationContainer)
            {
                try
                {
                    operationContainer.TryOperate(Name, operationContainer, out var _);
                    return true;
                }
                catch (Exception ex)
                {
                    Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}");
                    operationContainer.Result.AddDiagnostic(failure);
                    return false;
                }
            }

            public DataValue<string> Name { get; }

            protected override MorningGreetingCommand CreateInstance()
            {
                return new MorningGreetingCommand(Name);            }
        }
    }
}
