using DragonFruit2.GeneratorSupport;
using System;
using System.Collections.Generic;
using System.Text;
using Xunit;

namespace DragonFruit2.Generators.Test
{
    public class CodeCreationTests
    {

        [Fact]
        public async Task OutputsClassForCommandInfo()
        {
            var commandInfo = new CommandInfo
            {
                Name = "MyCommand",
                NamespaceName = "MyNamespace",
            };

            var expected = """"
                // <auto-generated />
                using DragonFruit2;
                using DragonFruit2.Common;
                using System.CommandLine;

                namespace MyNamespace
                {
                    /// <summary>
                    /// Auto-generated partial class for building CLI commands for <see cref="MyCommand" />
                    /// and creating a new MyCommand instance from a <see cref="System.CommandLine.ParseResult" />.
                    /// </summary>
                    public partial class MyCommand : CliArgs, ICliArgs<MyCommand>
                    {
                        private static MyArgsBuilder builder;

                        private class MyArgsBuilder
                        {
                            public System.CommandLine.Command Build()
                            {
                                var dataProvider = DataProviders.FirstOrDefault(dp => dp is CliDataProvider) as CliDataProvider;
 
                                var rootCommand = new System.CommandLine.Command("Test")
                                {
                                    Description = null
                                };

                            }
                        }

                        public static MyCommand Create(ParseResult parseResult)
                        {
                            var newArgs = new MyCommand()
                            {
                            };
                            return newArgs;
                        }
                    }
                }

                """";

            var actual = DragonFruit2Builder.GetSourceForCommandInfo(commandInfo);  

            Assert.Equal(expected, actual);
        }

        [Fact]
        public async Task OutputSetsCommandDescription()
        {
            var commandInfo = new CommandInfo
            {
                Name = "MyCommand",
                NamespaceName = "MyNamespace",
                Description = "This is my command"
            };

            var expected = """
                // <auto-generated />
                using DragonFruit2;
                using System.CommandLine;

                namespace MyNamespace
                {
                    public partial class MyCommand : IArgs<MyCommand>
                    {
                        public static System.CommandLine.Command CreateCli()
                        {
                            var rootCommand = new System.CommandLine.Command("Test")
                                {
                                    Description = "This is my command"
                                };
                """;

            var actual = DragonFruit2Builder.GetSourceForCommandInfo(commandInfo);
            actual = actual[..expected.Length]; // Trim to relevant part

            Assert.Equal(expected, actual);
        }

        [Fact]
        public async Task OutputsOptionDeclaration()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb,  propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OutputsOptionDescription()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
                Description = "This is my option"

            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = "This is my option",
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());

        }

        [Fact]
        public async Task OptionRequiredWhenModifier()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                HasRequiredModifier = true

            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = true
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OptionNotRequiredWhenNonNullableValueType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.Int32",
                IsValueType= true,
            };

            var expected = """
                var myOptionOption = new Option<System.Int32>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }

        [Fact]
        public async Task OptionRequiredWhenNonNullableReferenceType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                NullableAnnotation =  Microsoft.CodeAnalysis.NullableAnnotation.NotAnnotated,
            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = true
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);

                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }


        [Fact]
        public async Task OptionNotRequiredWhenNullableReferenceType()
        {
            var propInfo = new PropInfo
            {
                Name = "MyOption",
                TypeName = "System.String",
                NullableAnnotation = Microsoft.CodeAnalysis.NullableAnnotation.Annotated,
            };

            var expected = """
                var myOptionOption = new Option<System.String>("--my-option")
                {
                    Description = null,
                    Required = false
                };
                builder.AddNameLookup("MyOption", myOptionOption);
                rootCommand.Add(myOptionOption);
                
                """;

            var sb = new StringBuilder();
            DragonFruit2Builder.GetOptionDeclaration(sb, propInfo);

            Assert.Equal(expected, sb.ToString());
        }
    }
}
