using DragonFruit2.GeneratorSupport;
using Xunit;

namespace DragonFruit2.Generators.Test;

public class CommandInfoTheoryData : TheoryData<string, string, string, CommandInfo, string>
{
    public CommandInfoTheoryData()
    {
        Add("Empty args class",
            """
            public partial class MyArgs
            { }
            """,
            TestHelpers.EmptyConsoleAppCode,
            new CommandInfo()
            {
                Name = "MyArgs"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using DragonFruit2.Common;
            using System.CommandLine;

            /// <summary>
            /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
            /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
            /// </summary>
            public partial class MyArgs : CliArgs, ICliArgs<MyArgs>
            {
                public static System.CommandLine.Command CreateCli()
                {
                    builder ??= new MyArgsBuilder();
                    return builder.Build();
                }

                private static MyArgsBuilder builder;

                private class MyArgsBuilder
                {
                    public System.CommandLine.Command Build()
                    {
                        var dataProvider = DataProviders.FirstOrDefault(dp => dp is CliDataProvider) as CliDataProvider;

                        var rootCommand = new System.CommandLine.Command("Test")
                        {
                            Description = null,
                        };

                    }
                }

                public MyArgs()
                {
                }

                [SetsRequiredMembers()]
                private MyArgs()
                    : this()
                {
                }

                public static MyArgs Create()
                {

                    var newArgs = new MyArgs()
                    return newArgs;
                }

                public static MyArgs Create(ParseResult parseResult)
                {
                    SetCliDataProvider<MyArgs>(parseResult);
                    return Create();
                }
            }

            """);

        Add("Empty args struct",
            """
            public partial struct MyArgs
            { }
            """,
           TestHelpers.EmptyConsoleAppCode,
           new CommandInfo()
           {
               Name = "MyArgs",
               IsStruct = true,
           },
            """
            // <auto-generated />
            using DragonFruit2;
            using DragonFruit2.Common;
            using System.CommandLine;

            /// <summary>
            /// Auto-generated partial struct for building CLI commands for <see cref="MyArgs" />
            /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
            /// </summary>
            public partial struct MyArgs : CliArgs, ICliArgs<MyArgs>
            {
                public static System.CommandLine.Command CreateCli()
                {
                    builder ??= new MyArgsBuilder();
                    return builder.Build();
                }

                private static MyArgsBuilder builder;

                private class MyArgsBuilder
                {
                    public System.CommandLine.Command Build()
                    {
                        var dataProvider = DataProviders.FirstOrDefault(dp => dp is CliDataProvider) as CliDataProvider;

                        var rootCommand = new System.CommandLine.Command("Test")
                        {
                            Description = null,
                        };

                    }
                }

                public MyArgs()
                {
                }

                [SetsRequiredMembers()]
                private MyArgs()
                    : this()
                {
                }

                public static MyArgs Create()
                {

                    var newArgs = new MyArgs()
                    return newArgs;
                }

                public static MyArgs Create(ParseResult parseResult)
                {
                    SetCliDataProvider<MyArgs>(parseResult);
                    return Create();
                }
            }
            
            """);

        Add("Args w/ namespace (curly)",
            """
            namespace MyNamespace
            {
                public partial class MyArgs
                { }
            }
            """,
            TestHelpers.EmptyConsoleAppCodeWithArgsMyNamespace,
            new CommandInfo()
            {
                Name = "MyArgs",
                NamespaceName = "MyNamespace"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using DragonFruit2.Common;
            using System.CommandLine;

            namespace MyNamespace
            {
                /// <summary>
                /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
                /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
                /// </summary>
                public partial class MyArgs : CliArgs, ICliArgs<MyArgs>
                {
                    public static System.CommandLine.Command CreateCli()
                    {
                        builder ??= new MyArgsBuilder();
                        return builder.Build();
                    }

                    private static MyArgsBuilder builder;

                    private class MyArgsBuilder
                    {
                        public System.CommandLine.Command Build()
                        {
                            var dataProvider = DataProviders.FirstOrDefault(dp => dp is CliDataProvider) as CliDataProvider;

                            var rootCommand = new System.CommandLine.Command("Test")
                            {
                                Description = null,
                            };

                        }
                    }

                    public MyArgs()
                    {
                    }

                    [SetsRequiredMembers()]
                    private MyArgs()
                        : this()
                    {
                    }

                    public static MyArgs Create()
                    {

                        var newArgs = new MyArgs()
                        return newArgs;
                    }

                    public static MyArgs Create(ParseResult parseResult)
                    {
                        SetCliDataProvider<MyArgs>(parseResult);
                        return Create();
                    }
                }
            }
            
            """);

        Add("Args w/ namespace (semi-colon)",
            """
            namespace MyNamespace;
            public partial class MyArgs
            { }
            """,
            TestHelpers.EmptyConsoleAppCodeWithArgsMyNamespace,
            new CommandInfo()
            {
                Name = "MyArgs",
                NamespaceName = "MyNamespace"
            },
            """
            // <auto-generated />
            using DragonFruit2;
            using DragonFruit2.Common;
            using System.CommandLine;

            namespace MyNamespace
            {
                /// <summary>
                /// Auto-generated partial class for building CLI commands for <see cref="MyArgs" />
                /// and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
                /// </summary>
                public partial class MyArgs : CliArgs, ICliArgs<MyArgs>
                {
                    public static System.CommandLine.Command CreateCli()
                    {
                        builder ??= new MyArgsBuilder();
                        return builder.Build();
                    }

                    private static MyArgsBuilder builder;

                    private class MyArgsBuilder
                    {
                        public System.CommandLine.Command Build()
                        {
                            var dataProvider = DataProviders.FirstOrDefault(dp => dp is CliDataProvider) as CliDataProvider;

                            var rootCommand = new System.CommandLine.Command("Test")
                            {
                                Description = null,
                            };

                        }
                    }

                    public MyArgs()
                    {
                    }

                    [SetsRequiredMembers()]
                    private MyArgs()
                        : this()
                    {
                    }

                    public static MyArgs Create()
                    {

                        var newArgs = new MyArgs()
                        return newArgs;
                    }

                    public static MyArgs Create(ParseResult parseResult)
                    {
                        SetCliDataProvider<MyArgs>(parseResult);
                        return Create();
                    }
                }
            }
            
            """);


    }

}

