// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : ArgsRootBase<MyArgs>
{
    private List<Validator<int>>? ageValidators;

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string>? nameDataValue, DataValue<Int32>? ageDataValue, DataValue<string>? greetingDataValue)
        : this()
    {
        // TODO: Resolve nullable warning when changing to tstrongly yped DataValue
        if (ValueIsAvailable<string>(nameDataValue)) Name = nameDataValue.Value;
        if (ValueIsAvailable<int>(ageDataValue)) Age = ageDataValue.Value;
        if (ValueIsAvailable<string>(greetingDataValue)) Greeting = greetingDataValue.Value;


        static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
        {
            return dataValue switch
            {
                null => false,
                { IsSet: true } => true,
                _ => false
            };
        }
    }

    public override IEnumerable<Diagnostic> Validate()
    {
        var failures = new List<Diagnostic>();
        InitializeValidators();

        if (ageValidators is not null)
        {
            foreach (var validator in ageValidators)
            {
                failures.AddRange(validator.Validate(Age));
            }
        }

        return failures;
    }

    /// <summary>
    /// Initializes the collection of age validators with default validation rules.
    /// </summary>
    /// <remarks>
    /// This is a separate method because it will also be called by future code that 
    /// reports valdiation for extended help.
    /// </remarks>
    public void InitializeValidators()
    {
        ageValidators ??= new List<Validator<int>>();
        ageValidators.Add(new GreaterThanValidator<int>("Age", 0));

        // Other properties do not have validation, so their validators remain null.
    }

    static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

    //public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder,
    //                            CommandDataDefinition? parentCommandDataDefinition,
    //                            CommandDataDefinition? rootDataDefinition)
    //{
    //    return new MyArgs.MyArgsBuilder(parentCommandDataDefinition, rootDataDefinition);
    //}

    ///// <summary>
    ///// This static builder supplies the CLI declaration and filling the Result and 
    ///// return instance.
    ///// </summary>
    ///// <remarks>
    ///// The first type argument of the base is the Args type this builder creates, and the second is the root Args type. 
    ///// This means the two type arguments are the same for the root ArgsBuilder, but will differ for subcommand ArgsBuilders.
    ///// <br/>
    ///// Instances of this class are created in the <see IArgs.
    ///// </remarks>
    //internal class MyArgsBuilder : ArgsBuilder<MyArgs>
    //{
    //    //static MyArgsBuilder()
    //    //{
    //    //    ArgsBuilderCache<MyArgs>.AddArgsBuilder<MyArgs>(new MyArgsBuilder());
    //    //}

    //    public MyArgsBuilder(CommandDataDefinition? parentDataDefinition,
    //                         CommandDataDefinition? rootDataDefinition)
    //        : base(new MyArgsDataDefinition(parentDataDefinition, rootDataDefinition), () => new MyArgsDataValues())
    //    {
    //    }

    //    public override void Initialize(Builder<MyArgs> builder)
    //    {
    //        // Generate for each data provider
    //        InitializeCli(builder, builder.GetDataProvider<CliDataProvider<MyArgs>>());
    //        InitializeDefaults(builder, builder.GetDataProvider<DefaultDataProvider<MyArgs>>());
    //    }

    //    public override Command InitializeCli(Builder<MyArgs> builder, CliDataProvider<MyArgs>? cliDataProvider)
    //    {
    //        if (cliDataProvider is null) throw new ArgumentNullException(nameof(cliDataProvider));

    //        var rootCommand = new System.CommandLine.Command("Test")
    //        {
    //            Description = "This is a test command"
    //        };
    //        var nameOption = new Option<string>("--name")
    //        {
    //            Description = "Your name",
    //            Required = true
    //        };
    //        cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Name)), nameOption);
    //        rootCommand.Add(nameOption);

    //        var ageOption = new Option<System.Int32>("--age")
    //        {
    //            Description = "Your Age"
    //        };
    //        cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Age)), ageOption);
    //        rootCommand.Add(ageOption);

    //        var greetingOption = new Option<System.String>("--greeting")
    //        {
    //            Description = "Greeting message"
    //        };
    //        cliDataProvider.AddNameLookup((typeof(MyArgs), nameof(MyArgs.Greeting)), greetingOption);
    //        rootCommand.Add(greetingOption);

    //        rootCommand.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 0; });

    //        cliDataProvider.RootCommand = rootCommand;

    //        return rootCommand;
    //    }

    //    private void InitializeDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs>? defaultDataProvider)
    //    {
    //        if (defaultDataProvider is null) return;

    //        // RegisterDefaults for attribute values and initialization

    //        RegisterCustomDefaults(builder, defaultDataProvider);
    //    }

    //    protected override IEnumerable<Diagnostic> CheckRequiredValues(DataValues dataValues)
    //    {
    //        if (dataValues is not MyArgsDataValues typedDataValues)
    //        {
    //            throw new InvalidOperationException("Internal error: passed incorrect data values");
    //        }

    //        var requiredFailures = new List<Diagnostic>();
    //        AddRequiredFailureIfNeeded<string>(requiredFailures, !typedDataValues.Name.IsSet, nameof(typedDataValues.Name));
    //        return requiredFailures
    //                .Where(x => x is not null)
    //                .Select(x => x!);
    //    }
    //}

    // Generation Note: MyArgs in the class declaration is TArgs.
    public class MyArgsDataDefinition : CommandDataDefinition<MyArgs>
    {
        // Generation Note: MyArgs in the following constructor is TArgs.
        public MyArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition, () => new MyArgsDataValues())
        {
            var argsType = typeof(MyArgs);
            Add(new OptionDataDefinition(argsType, nameof(Name))
            {
                DataType = typeof(string),
                IsRequired = true,
            });
            Add(new OptionDataDefinition(argsType ,nameof(Age))
            {
                DataType = typeof(int),
                IsRequired = false,
            });
            Add(new OptionDataDefinition(argsType, nameof(Greeting))
            {
                DataType = typeof(string),
                IsRequired = false,
            });
        }
    }

    // Generation Note: MyArgs in the following class is TRootArgs, except for the private srgsType.
    public class MyArgsDataValues : DataValues<MyArgs>
    {
        public override void SetDataValues(DataProvider<MyArgs> dataProvider)
        {
            dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Name)), Name);
            dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Age)), Age);
            dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Greeting)), Greeting);
        }

        private Type argsType = typeof(MyArgs);

        public DataValue<string> Name { get; } = DataValue<string>.Create(nameof(Name), typeof(MyArgs));
        public DataValue<int> Age { get; } = DataValue<int>.Create(nameof(Age), typeof(int));
        public DataValue<string> Greeting { get; } = DataValue<string>.Create(nameof(Greeting), typeof(string));

        protected override MyArgs CreateInstance()
        {
            return new MyArgs(Name, Age, Greeting);
        }
    }
}
