// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;
using System.Net.Cache;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : ArgsRootBase<MyArgs>
{
    private List<Validator<int>>? ageValidators;

    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string>? nameDataValue, DataValue<Int32>? ageDataValue, DataValue<string>? greetingDataValue)
        : this()
    {
        // TODO: Resolve nullable warning when changing to tstrongly yped DataValue
        if (ValueIsAvailable<string>(nameDataValue)) Name = nameDataValue.Value;
        if (ValueIsAvailable<int>(ageDataValue)) Age = ageDataValue.Value;
        if (ValueIsAvailable<string>(greetingDataValue)) Greeting = greetingDataValue.Value;


        static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
        {
            return dataValue switch
            {
                null => false,
                { IsSet: true } => true,
                _ => false
            };
        }
    }

    public override IEnumerable<Diagnostic> Validate()
    {
        var failures = new List<Diagnostic>();
        InitializeValidators();

        if (ageValidators is not null)
        {
            foreach (var validator in ageValidators)
            {
                failures.AddRange(validator.Validate(Age));
            }
        }

        return failures;
    }

    /// <summary>
    /// Initializes the collection of age validators with default validation rules.
    /// </summary>
    /// <remarks>
    /// This is a separate method because it will also be called by future code that 
    /// reports valdiation for extended help.
    /// </remarks>
    public void InitializeValidators()
    {
        ageValidators ??= new List<Validator<int>>();
        ageValidators.Add(new GreaterThanValidator<int>("Age", 0));

        // Other properties do not have validation, so their validators remain null.
    }

    static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

    // Generation Note: MyArgs in the class declaration is TArgs.
    public partial class MyArgsDataDefinition : CommandDataDefinition<MyArgs>
    {
        // Generation Note: MyArgs in the following constructor is TArgs.
        public MyArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            GetDataValues = () => new MyArgsDataValues(this);

            Name = new OptionDataDefinition<string>(this, nameof(Name))
            {
                DataType = typeof(string),
                IsRequired = true,
            };
            Add(Name);
            Age = new OptionDataDefinition<int>(this, nameof(Age))
            {
                DataType = typeof(int),
                IsRequired = false,
            };
            Add(Age);
            Greeting = new OptionDataDefinition<string>(this, nameof(Greeting))
            {
                DataType = typeof(string),
                IsRequired = false,
            };
            Add(Greeting);

            RegisterCustomizations();
        }

        public OptionDataDefinition<string> Name { get; }
        public OptionDataDefinition<int> Age { get; }
        public OptionDataDefinition<string> Greeting { get; }

        public override IEnumerable<TReturn> CreateFromMembers<TReturn>(ICreatesFromMembers<TReturn> dataProvider)
        {
            return new List<TReturn> {
                dataProvider.CreateFromMember<string>(this, nameof(Name)),
                dataProvider.CreateFromMember<int>(this,nameof(Age)),
                dataProvider.CreateFromMember<string>(this,nameof(Greeting)),
            };
        }
    }

    // Generation Note: MyArgs in the following class is TRootArgs, except for the private srgsType.
    public class MyArgsDataValues : DataValues<MyArgs>
    {
        public MyArgsDataValues(MyArgsDataDefinition commandDefinition)
            : base(commandDefinition)
        {
            Name = DataValue<string>.Create(nameof(Name), argsType, commandDefinition.Name);
            Add(Name);
            Age = DataValue<int>.Create(nameof(Age), argsType, commandDefinition.Age);
            Add(Age);
            Greeting = DataValue<string>.Create(nameof(Greeting), argsType, commandDefinition.Greeting);
            Add(Greeting);
        }

        public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
        {
            if (Name is not null && !Name.IsSet)
            {
                dataProvider.TrySetDataValue(Name, result);
            }
            if (Age is not null && !Age.IsSet)
            {
                dataProvider.TrySetDataValue(Age, result);
            }
            if (Greeting is not null && !Greeting.IsSet)
            {
                dataProvider.TrySetDataValue(Greeting, result);
            }
        }

        private Type argsType = typeof(MyArgs);

        public DataValue<string> Name { get; }
        public DataValue<int> Age { get; }
        public DataValue<string> Greeting { get; }

        protected override MyArgs CreateInstance()
        {
            return new MyArgs(Name, Age, Greeting);
        }
    }
}
