// <auto-generated />
#nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;
using System.Net.Cache;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
public partial class MyArgs : ArgsRootBase<MyArgs>
{
    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyArgs()
    {
    }

    [SetsRequiredMembers()]
    private MyArgs(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        // TODO: Resolve nullable warning. This appears in generated code and needs to be resolved.(Issue: #48)
        if (ValueIsAvailable<string>(nameDataValue)) Name = nameDataValue.Value;
        if (ValueIsAvailable<int>(ageDataValue)) Age = ageDataValue.Value;
        if (ValueIsAvailable<string>(greetingDataValue)) Greeting = greetingDataValue.Value;

        // This is generated because it should not be used outside the constructor.
        static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
        {
            return dataValue switch
            {
                null => false,
                { IsSet: true } => true,
                _ => false
            };
        }
    }

    static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

    // Generation Note: MyArgs in the class declaration is TArgs.
    public partial class MyArgsDataDefinition : CommandDataDefinition<MyArgs>
    {
        // Generation Note: MyArgs in the following constructor is TArgs.
        public MyArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            GetDataValues = () => new MyArgsDataValues(this);

            Name = new OptionDataDefinition<string>(this, nameof(Name))
            {
                DataType = typeof(string),
                IsRequired = true,
            };

            Age = new OptionDataDefinition<int>(this, nameof(Age))
            {
                DataType = typeof(int),
                IsRequired = false,
            };
            Age.RegisterValidator(new GreaterThanValidator<int>(Age.DefinitionName, 0));

            Greeting = new OptionDataDefinition<string>(this, nameof(Greeting))
            {
                DataType = typeof(string),
                IsRequired = false,
            };

            RegisterCustomizations();
        }


        public OptionDataDefinition<string> Name { get; }
        public OptionDataDefinition<int> Age { get; }
        public OptionDataDefinition<string> Greeting { get; }

        protected override MemberDataDefinition? GetMemberDefinition(string memberName)
        {
            return memberName switch
            {
                nameof(Name) => Name,
                nameof(Age) => Name,
                nameof(Greeting) => Name,
                _ => null
            };
        }

        public override IEnumerable<TReturn> Operate<TReturn>(IOperationOnMemberDefinition<TReturn> operationContainer)
        {
            var retValues = new TReturn[3];
            retValues[0] = operationContainer.Operate(Name);
            retValues[1] = operationContainer.Operate(Age);
            retValues[2] = operationContainer.Operate(Greeting);
            return retValues;
        }
    }

    // Generation Note: MyArgs in the following class is TRootArgs, except for the private srgsType.
    public class MyArgsDataValues : DataValues<MyArgs>
    {
        public MyArgsDataValues(MyArgsDataDefinition commandDefinition)
            : base(commandDefinition)
        {
            Name = DataValue<string>.Create(nameof(Name), argsType, this, commandDefinition.Name);
            Add(Name);
            Age = DataValue<int>.Create(nameof(Age), argsType, this, commandDefinition.Age);
            Add(Age);
            Greeting = DataValue<string>.Create(nameof(Greeting), argsType, this, commandDefinition.Greeting);
            Add(Greeting);
        }

        public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
        {
            if (Name is not null && !Name.IsSet)
            {
                dataProvider.TrySetDataValue(Name, result);
            }
            if (Age is not null && !Age.IsSet)
            {
                dataProvider.TrySetDataValue(Age, result);
            }
            if (Greeting is not null && !Greeting.IsSet)
            {
                dataProvider.TrySetDataValue(Greeting, result);
            }
        }

        private Type argsType = typeof(MyArgs);

        public DataValue<string> Name { get; }
        public DataValue<int> Age { get; }
        public DataValue<string> Greeting { get; }

        protected override MyArgs CreateInstance()
        {
            return new MyArgs(Name, Age, Greeting);
        }

    }
}
