// <auto-generated />
#nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Net.Cache;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;

namespace SampleConsoleApp;

/// <summary>
/// 
/// </summary>
partial class MyCommand 
{
    // Only generate the following constructor if there are no other constructors defined (possibly via partial constructor)
    public MyCommand()
    {
    }

    [SetsRequiredMembers()]
    private MyCommand(DataValue<string> nameDataValue, DataValue<Int32> ageDataValue, DataValue<string> greetingDataValue)
        : this()
    {
        // TODO: Resolve nullable warning. This appears in generated code and needs to be resolved.(Issue: #48)
        if (ValueIsAvailable<string>(nameDataValue)) Name = nameDataValue.Value;
        if (ValueIsAvailable<int>(ageDataValue)) Age = ageDataValue.Value;
        if (ValueIsAvailable<string>(greetingDataValue)) Greeting = greetingDataValue.Value;

        // This is generated because it should not be used outside the constructor.
        static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
        {
            return dataValue switch
            {
                null => false,
                { IsSet: true } => true,
                _ => false
            };
        }
    }

    static partial void RegisterCustomDefaults(Builder<MyCommand> builder, DefaultDataProvider<MyCommand> defaultDataProvider);

    // Generation Note: MyCommand in the class declaration is TCommand.
    public partial class MyCommandDataDefinition : CommandDataDefinition<MyCommand, MyCommand>
    {
        public static MyCommandDataDefinition Instance = new(null, null);

        // Generation Note: MyCommand in the following constructor is TCommand.
        public MyCommandDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            GetDataValues = () => new MyCommandDataValues();

            Name = new OptionDataDefinition<string>(this, nameof(Name))
            {
                DataType = typeof(string),
                IsRequired = true,
            };
            Name.RegisterValidator(new RequiredValidator<string>(Name.DefinitionName));

            Age = new OptionDataDefinition<int>(this, nameof(Age))
            {
                DataType = typeof(int),
                IsRequired = false,
            };
            Age.RegisterValidator(new GreaterThanValidator<int>(Age.DefinitionName, 0));
            Age.RegisterValidator(new RequiredValidator<int>(Age.DefinitionName));

            Greeting = new OptionDataDefinition<string>(this, nameof(Greeting))
            {
                DataType = typeof(string),
                IsRequired = false,
            };

            RegisterCustomizations();
        }

        public OptionDataDefinition<string> Name { get; }
        public OptionDataDefinition<int> Age { get; }
        public OptionDataDefinition<string> Greeting { get; }

        protected override MemberDataDefinition? GetMemberDefinition(string memberName)
        {
            return memberName switch
            {
                nameof(Name) => Name,
                nameof(Age) => Name,
                nameof(Greeting) => Name,
                _ => null
            };
        }

        public override IEnumerable<TReturn> Operate<TReturn>(IOperationOnMemberDefinition<TReturn> operationContainer)
        {
            var retValues = new TReturn[3];
            retValues[0] = operationContainer.Operate(Name);
            retValues[1] = operationContainer.Operate(Age);
            retValues[2] = operationContainer.Operate(Greeting);
            return retValues;
        }
    }

    // Generation Note: MyCommand in the following class is TRootCommand, except for the private srgsType.
    public class MyCommandDataValues : DataValues<MyCommand>
    {
        public static MyCommandDataDefinition CommandDataDefinition = MyCommandDataDefinition.Instance;
        private Type commandClassType = typeof(MyCommand);

        public MyCommandDataValues()
            : base()
        {
            Name = DataValue<string>.Create(nameof(Name), commandType, this, CommandDataDefinition.Name);
            Add(Name);
            Age = DataValue<int>.Create(nameof(Age), commandType, this, CommandDataDefinition.Age);
            Add(Age);
            Greeting = DataValue<string>.Create(nameof(Greeting), commandType, this, CommandDataDefinition.Greeting);
            Add(Greeting);
        }

        public override bool Operate<TReturn>(IOperateOnDataValue<MyCommand, TReturn> operationContainer)
        {
            try
            {
                operationContainer.TryOperate(Name, operationContainer, out var _);
                operationContainer.TryOperate(Age, operationContainer, out var _);
                operationContainer.TryOperate(Greeting, operationContainer, out var _);
                return true;
            }
            catch (Exception ex)
            {
                Diagnostic failure = new(DiagnosticId.UnexpectedException.ToValidationIdString(), DiagnosticSeverity.Error, $"An unexpected error occurred while operating on data values in the {operationContainer.OperationName}. The error was {ex.Message}");
                operationContainer.Result.AddDiagnostic(failure);
                return false;
            }
        }

        private Type commandType = typeof(MyCommand);

        public DataValue<string> Name { get; }
        public DataValue<int> Age { get; }
        public DataValue<string> Greeting { get; }

        protected override MyCommand CreateInstance()
        {
            return new MyCommand(Name, Age, Greeting);
        }

    }
}
