//HintName: EveningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="EveningGreetingArgs"/>" and creating a new EveningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class EveningGreetingArgs : MyArgs
    {
        private List<Validator<int>>? ageValidators;


        public EveningGreetingArgs()
        {
        }
        [SetsRequiredMembers()]
        protected EveningGreetingArgs(DataValue<int>? ageDataValue, DataValue<string>? nameDataValue)
            : base(nameDataValue)
        {
            if (ValueIsAvailable(ageDataValue)) Age = ageDataValue.Value;

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();

            if (ageValidators is not null)
            {
                foreach (var validator in ageValidators)
                {
                    failures.AddRange(validator.Validate(Age));
                }
            }

            return failures;
        }

        private void InitializeValidators()
        {
            ageValidators ??= new List<Validator<int>>();
            ageValidators.Add(new GreaterThanValidator<int>("Age",             0, null            ));

        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder, CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
        {
            return new EveningGreetingArgs.EveningGreetingArgsArgsBuilder(parentDataDefinition, rootDataDefinition);
        }

        /// <summary>
        ///  This static builder supplies the CLI declaration and filling the Result and return instance.
        /// </summary>
        internal class EveningGreetingArgsArgsBuilder : ArgsBuilder<MyArgs>
        {

            public EveningGreetingArgsArgsBuilder(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(new EveningGreetingArgsDataDefinition(parentDataDefinition, rootDataDefinition), () => new EveningGreetingArgsDataValues())
            {
            }

            public override void Initialize(Builder<MyArgs> builder)
            {
                InitializeCli(builder, builder.GetDataProvider<CliDataProvider<MyArgs>>());
                InitializeDefaults(builder, builder.GetDataProvider<DefaultDataProvider<MyArgs>>());
            }

            public override Command InitializeCli(Builder<MyArgs> builder, CliDataProvider<MyArgs>? cliDataProvider)
            {
                var cmd = new System.CommandLine.Command("evening-greeting")
                {
                };

                var ageOption = new Option<int>("--age")
                {
                    Description = null,
                    Required = false,
                    Recursive=true
                };
                cliDataProvider.AddNameLookup((typeof(EveningGreetingArgs), nameof(Age)), ageOption);
                cmd.Add(ageOption);

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 25; });
                return cmd;
            }

            public void InitializeDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs>? defaultDataProvider)
            {
                if (defaultDataProvider is null) return;
                // TODO: Register defaults based on attributes, initializer, and the RegisterDefault calls
                RegisterCustomDefaults(builder, defaultDataProvider);
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(DataValues dataValues)
            {
                if (dataValues is not EveningGreetingArgsDataValues typedDataValues)
                {
                    throw new InvalidOperationException("Internal error: passed incorrect data values");
                }
                var requiredFailures = new List<ValidationFailure?>();
                return requiredFailures
                          .Where(x => x is not null)
                          .Select(x => x!);
            }
        }

        public class EveningGreetingArgsDataValues : DataValues<MyArgs>
        {

            public override void SetDataValues(DataProvider<MyArgs> dataProvider)
            {
                dataProvider.TrySetDataValue((typeof(EveningGreetingArgs), nameof(Age)), Age);
                dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Name)), Name);
            }

            private Type argsType = typeof(EveningGreetingArgs);
            public DataValue<int> Age { get; } = DataValue<int>.Create(nameof(Age), typeof(EveningGreetingArgs));
            public DataValue<string> Name { get; } = DataValue<string>.Create(nameof(Name), typeof(EveningGreetingArgs));

            protected override EveningGreetingArgs CreateInstance()
            {
                return new EveningGreetingArgs(Age, Name);            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        internal class EveningGreetingArgsDataDefinition : CommandDataDefinition<EveningGreetingArgs>
        {

            public EveningGreetingArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                string fullArgsName = typeof(MyNamespace.EveningGreetingArgs).FullName!;
                Add(new OptionDataDefinition(fullArgsName + nameof(Age))
                {
                    DataType = typeof(int), 
                    IsRequired = false, 
                });
            }

        }
    }
}
