//HintName: MyOtherArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Auto-generated partial class for building CLI commands for <see cref="MyOtherArgs"/>" and creating a new MyOtherArgs instance from a <see cref="System.CommandLine.ParseResult" />.
/// </summary>
public partial class MyOtherArgs : ArgsRootBase<MyOtherArgs>
{

    [SetsRequiredMembers()]
    protected MyOtherArgs()
    {
    }

    static partial void RegisterCustomDefaults(Builder<MyOtherArgs> builder, DefaultDataProvider<MyOtherArgs> defaultDataProvider);

    /// <summary>
    ///  The data definition is available to data providers and are used for initialization.
    /// </summary>
    public partial class MyOtherArgsDataDefinition : CommandDataDefinition<MyOtherArgs>
    {

        public MyOtherArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            GetDataValues = () => new MyOtherArgsDataValues(this);
            RegisterCustomizations();
        }

        protected override MemberDataDefinition? GetMemberDefinition(string memberName)
        {
            return memberName switch
            {
            };
        }

        public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
        {
            var retValues = new TReturn[0];
            return retValues;
        }

    }

    public class MyOtherArgsDataValues : DataValues<MyOtherArgs>
    {

        public MyOtherArgsDataValues(MyOtherArgsDataDefinition commandDefinition)
            : base(commandDefinition)
        {
        }

        public override void SetDataValues(DataProvider<MyOtherArgs> dataProvider, Result<MyOtherArgs> result)
        {
        }

        private Type argsType = typeof(MyOtherArgs);

        protected override MyOtherArgs CreateInstance()
        {
            return new MyOtherArgs();        }
    }
}
