//HintName: MorningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MorningGreetingArgs"/>" and creating a new MorningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class MorningGreetingArgs : MyArgs
    {

        [SetsRequiredMembers()]
        protected MorningGreetingArgs(DataValue<string>? nameDataValue)
            : base(nameDataValue)
        {

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<Diagnostic> Validate()
        {
            var failures = new List<Diagnostic>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public class MorningGreetingArgsDataValues : DataValues<MyArgs>
        {

            public MorningGreetingArgsDataValues(MorningGreetingArgsDataDefinition commandDefinition)
                : base(commandDefinition)
            {
            }

            public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
            {
                if (Name is not null && !Name.IsSet)
                {
                    dataProvider.TrySetDataValue(Name, result);
                }
            }

            private Type argsType = typeof(MorningGreetingArgs);
            public DataValue<string> Name { get; }

            protected override MorningGreetingArgs CreateInstance()
            {
                return new MorningGreetingArgs(Name);            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class MorningGreetingArgsDataDefinition : CommandDataDefinition<MyArgs>
        {

            public MorningGreetingArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new MorningGreetingArgsDataValues(this);
                RegisterCustomizations();
            }

            public override IEnumerable<TReturn> CreateMembers<TReturn>(ICreatesMembers<TReturn> dataProvider)
            {
                return new List<TReturn>
                {
                };
            }

        }
    }
}
