//HintName: MyArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Auto-generated partial class for building CLI commands for <see cref="MyArgs"/>" and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
/// </summary>
public partial class MyArgs : ArgsRootBase<MyArgs>
{

    [SetsRequiredMembers()]
    protected MyArgs()
    {
    }

    static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

    /// <summary>
    ///  The data definition is available to data providers and are used for initialization.
    /// </summary>
    public partial class MyArgsDataDefinition : CommandDataDefinition<MyArgs>
    {

        public MyArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            GetDataValues = () => new MyArgsDataValues(this);
            RegisterCustomizations();
        }

        protected override MemberDataDefinition? GetMemberDefinition(string memberName)
        {
            return memberName switch
            {
            };
        }

        public override IEnumerable<TReturn> Operate<TReturn> (IOperationOnMemberDefinition<TReturn> operationContainer)
        {
            var retValues = new TReturn[0];
            return retValues;
        }

    }

    public class MyArgsDataValues : DataValues<MyArgs>
    {

        public MyArgsDataValues(MyArgsDataDefinition commandDefinition)
            : base(commandDefinition)
        {
        }

        public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
        {
        }

        private Type argsType = typeof(MyArgs);

        protected override MyArgs CreateInstance()
        {
            return new MyArgs();        }
    }
}
