//HintName: Bar.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="Bar"/>" and creating a new Bar instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class Bar : EveningGreetingArgs
    {

        [SetsRequiredMembers()]
        protected Bar(DataValue<int>? ageDataValue, DataValue<string>? nameDataValue)
            : base(ageDataValue, nameDataValue)
        {

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder, CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
        {
            return new Bar.BarArgsBuilder(parentDataDefinition, rootDataDefinition);
        }

        /// <summary>
        ///  This static builder supplies the CLI declaration and filling the Result and return instance.
        /// </summary>
        internal class BarArgsBuilder : ArgsBuilder<MyArgs>
        {

            public BarArgsBuilder(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(new BarDataDefinition(parentDataDefinition, rootDataDefinition), () => new BarDataValues())
            {
            }

            public override void Initialize(Builder<MyArgs> builder)
            {
                InitializeCli(builder, builder.GetDataProvider<CliDataProvider<MyArgs>>());
                InitializeDefaults(builder, builder.GetDataProvider<DefaultDataProvider<MyArgs>>());
            }

            public override Command InitializeCli(Builder<MyArgs> builder, CliDataProvider<MyArgs>? cliDataProvider)
            {
                var cmd = new System.CommandLine.Command("bar")
                {
                };

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 22; });
                return cmd;
            }

            public void InitializeDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs>? defaultDataProvider)
            {
                if (defaultDataProvider is null) return;
                // TODO: Register defaults based on attributes, initializer, and the RegisterDefault calls
                RegisterCustomDefaults(builder, defaultDataProvider);
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(DataValues dataValues)
            {
                if (dataValues is not BarDataValues typedDataValues)
                {
                    throw new InvalidOperationException("Internal error: passed incorrect data values");
                }
                var requiredFailures = new List<ValidationFailure?>();
                return requiredFailures
                          .Where(x => x is not null)
                          .Select(x => x!);
            }
        }

        public class BarDataValues : DataValues<MyArgs>
        {

            public override void SetDataValues(DataProvider<MyArgs> dataProvider)
            {
                dataProvider.TrySetDataValue((typeof(EveningGreetingArgs), nameof(Age)), Age);
                dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Name)), Name);
            }

            private Type argsType = typeof(Bar);
            public DataValue<int> Age { get; } = DataValue<int>.Create(nameof(Age), typeof(Bar));
            public DataValue<string> Name { get; } = DataValue<string>.Create(nameof(Name), typeof(Bar));

            protected override Bar CreateInstance()
            {
                return new Bar(Age, Name);            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        internal class BarDataDefinition : CommandDataDefinition<Bar>
        {

            public BarDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                string fullArgsName = typeof(MyNamespace.Bar).FullName!;
            }

        }
    }
}
