//HintName: MyArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MyArgs"/>" and creating a new MyArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class MyArgs : ArgsRootBase<MyArgs>
    {

        [SetsRequiredMembers()]
        protected MyArgs()
        {

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<Diagnostic> Validate()
        {
            var failures = new List<Diagnostic>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public class MyArgsDataValues : DataValues<MyArgs>
        {

            public MyArgsDataValues(MyArgsDataDefinition commandDefinition)
                : base(commandDefinition)
            {
            }

            public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
            {
            }

            private Type argsType = typeof(MyArgs);

            protected override MyArgs CreateInstance()
            {
                return new MyArgs();            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class MyArgsDataDefinition : CommandDataDefinition<MyArgs>
        {

            public MyArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new MyArgsDataValues(this);
                RegisterCustomizations();
            }

            public override IEnumerable<TReturn> CreateFromMembers<TReturn>(ICreatesFromMembers<TReturn> dataProvider)
            {
                return new List<TReturn>
                {
                };
            }

        }
    }
}
