//HintName: EveningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="EveningGreetingArgs"/>" and creating a new EveningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class EveningGreetingArgs : MyArgs
    {


        public EveningGreetingArgs()
        {
        }
        [SetsRequiredMembers()]
        protected EveningGreetingArgs(DataValue<int>? ageDataValue, DataValue<string>? nameDataValue)
            : base(nameDataValue)
        {
            if (ValueIsAvailable(ageDataValue)) Age = ageDataValue.Value;

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<Diagnostic> Validate()
        {
            var failures = new List<Diagnostic>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public class EveningGreetingArgsDataValues : DataValues<MyArgs>
        {

            public EveningGreetingArgsDataValues(EveningGreetingArgsDataDefinition commandDefinition)
                : base(commandDefinition)
            {
                Age = DataValue<int>.Create(nameof(Age), argsType, commandDefinition.Age);
                Add(Age);
            }

            public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
            {
                if (Age is not null && !Age.IsSet)
                {
                    dataProvider.TrySetDataValue(Age, result);
                }
                if (Name is not null && !Name.IsSet)
                {
                    dataProvider.TrySetDataValue(Name, result);
                }
            }

            private Type argsType = typeof(EveningGreetingArgs);
            public DataValue<int> Age { get; }
            public DataValue<string> Name { get; }

            protected override EveningGreetingArgs CreateInstance()
            {
                return new EveningGreetingArgs(Age, Name);            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class EveningGreetingArgsDataDefinition : CommandDataDefinition<MyArgs>
        {

            public EveningGreetingArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new EveningGreetingArgsDataValues(this);
                Age = new OptionDataDefinition<int>(this, nameof(Age))
                {
                    DataType = typeof(int), 
                    IsRequired = false, 
                };
                Add(Age);
                Add(new Bar.BarDataDefinition(this, this.RootDataDefinition)
                {
                });
                RegisterCustomizations();
            }
            public OptionDataDefinition<int> Age { get; }

            public override IEnumerable<TReturn> CreateMembers<TReturn>(ICreatesMembers<TReturn> dataProvider)
            {
                return new List<TReturn>
                {
                    dataProvider.CreateMember<int>(this, nameof(Age)),
                };
            }

        }
    }
}
