//HintName: MorningGreetingArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="MorningGreetingArgs"/>" and creating a new MorningGreetingArgs instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class MorningGreetingArgs : MyArgs
    {

        [SetsRequiredMembers()]
        protected MorningGreetingArgs(DataValue<string>? nameDataValue)
            : base(nameDataValue)
        {

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<ValidationFailure> Validate()
        {
            var failures = new List<ValidationFailure>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public static ArgsBuilder<MyArgs> GetArgsBuilder(Builder<MyArgs> builder)
        {
            return new MorningGreetingArgs.MorningGreetingArgsArgsBuilder();
        }

        /// <summary>
        ///  This static builder supplies the CLI declaration and filling the Result and return instance.
        /// </summary>
        /// <remarks>
        ///  The first type argument of the base is the Args type this builder creates, and the second is the root Args type. This means the two type arguments are the same for the root ArgsBuilder, but will differ for subcommand ArgsBuilders.
        /// </remarks>
        internal class MorningGreetingArgsArgsBuilder : ArgsBuilder<MyArgs>
        {

            public override void Initialize(Builder<MyArgs> builder)
            {
                InitializeCli(builder, builder.GetDataProvider<CliDataProvider<MyArgs>>());
                InitializeDefaults(builder, builder.GetDataProvider<DefaultDataProvider<MyArgs>>());
            }

            public override Command InitializeCli(Builder<MyArgs> builder, CliDataProvider<MyArgs>? cliDataProvider)
            {
                var cmd = new System.CommandLine.Command("morning-greeting")
                {
                    Description = null,
                };

                cmd.SetAction(p => { ArgsBuilderCache<MyArgs>.ActiveArgsBuilder = this; return 25; });
                return cmd;
            }

            public void InitializeDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs>? defaultDataProvider)
            {
                if (defaultDataProvider is null) return;
                // TODO: Register defaults based on attributes, initializer, and the RegisterDefault calls
                RegisterCustomDefaults(builder, defaultDataProvider);
            }


            protected override IEnumerable<ValidationFailure> CheckRequiredValues(DataValues dataValues)
            {
                if (dataValues is not MorningGreetingArgsDataValues typedDataValues)
                {
                    throw new InvalidOperationException("Internal error: passed incorrect data values");
                }
                var requiredFailures = new List<ValidationFailure?>();
                return requiredFailures
                          .Where(x => x is not null)
                          .Select(x => x!);
            }

            protected override DataValues<MyArgs> CreateDataValues()
            {
                return new MorningGreetingArgsDataValues();
            }

            protected override MyArgs CreateInstance(DataValues dataValues)
            {
                if (dataValues is not MorningGreetingArgsDataValues typedDataValues)
                {
                    throw new InvalidOperationException("Internal error: passed incorrect data values");
                }

                return new MorningGreetingArgs(typedDataValues.Name);            }
        }

        public class MorningGreetingArgsDataValues : DataValues<MyArgs>
        {

            public override void SetDataValues(DataProvider<MyArgs> dataProvider)
            {
                dataProvider.TrySetDataValue((typeof(MyArgs), nameof(Name)), Name);
            }

            private Type argsType = typeof(MorningGreetingArgs);
            public DataValue<string> Name { get; } = DataValue<string>.Create(nameof(Name), typeof(MorningGreetingArgs));
        }
    }
}
