//HintName: MyOtherArgs.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

/// <summary>
/// Auto-generated partial class for building CLI commands for <see cref="MyOtherArgs"/>" and creating a new MyOtherArgs instance from a <see cref="System.CommandLine.ParseResult" />.
/// </summary>
public partial class MyOtherArgs : ArgsRootBase<MyOtherArgs>
{

    [SetsRequiredMembers()]
    protected MyOtherArgs()
    {

        static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
        {
            return dataValue switch
            {
                null => false,
                { IsSet: true } => true,
                _ => false
            };
        }
    }

    public IEnumerable<ValidationFailure> Validate()
    {
        var failures = new List<ValidationFailure>();
        InitializeValidators();


        return failures;
    }

    private void InitializeValidators()
    {
    }

    static partial void RegisterCustomDefaults(Builder<MyOtherArgs> builder, DefaultDataProvider<MyOtherArgs> defaultDataProvider);

    public static ArgsBuilder<MyOtherArgs> GetArgsBuilder(Builder<MyOtherArgs> builder, CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
    {
        return new MyOtherArgs.MyOtherArgsArgsBuilder(parentDataDefinition, rootDataDefinition);
    }

    /// <summary>
    ///  This static builder supplies the CLI declaration and filling the Result and return instance.
    /// </summary>
    internal class MyOtherArgsArgsBuilder : ArgsBuilder<MyOtherArgs>
    {

        public MyOtherArgsArgsBuilder(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(new MyOtherArgsDataDefinition(parentDataDefinition, rootDataDefinition), () => new MyOtherArgsDataValues())
        {
        }

        public override void Initialize(Builder<MyOtherArgs> builder)
        {
            InitializeCli(builder, builder.GetDataProvider<CliDataProvider<MyOtherArgs>>());
            InitializeDefaults(builder, builder.GetDataProvider<DefaultDataProvider<MyOtherArgs>>());
        }

        public override Command InitializeCli(Builder<MyOtherArgs> builder, CliDataProvider<MyOtherArgs>? cliDataProvider)
        {
            var cmd = new System.CommandLine.RootCommand("my-other")
            {
            };

            cmd.SetAction(p => { ArgsBuilderCache<MyOtherArgs>.ActiveArgsBuilder = this; return ; });
            cliDataProvider.RootCommand = cmd;
            return cmd;
        }

        public void InitializeDefaults(Builder<MyOtherArgs> builder, DefaultDataProvider<MyOtherArgs>? defaultDataProvider)
        {
            if (defaultDataProvider is null) return;
            // TODO: Register defaults based on attributes, initializer, and the RegisterDefault calls
            RegisterCustomDefaults(builder, defaultDataProvider);
        }


        protected override IEnumerable<ValidationFailure> CheckRequiredValues(DataValues dataValues)
        {
            if (dataValues is not MyOtherArgsDataValues typedDataValues)
            {
                throw new InvalidOperationException("Internal error: passed incorrect data values");
            }
            var requiredFailures = new List<ValidationFailure?>();
            return requiredFailures
                      .Where(x => x is not null)
                      .Select(x => x!);
        }
    }

    public class MyOtherArgsDataValues : DataValues<MyOtherArgs>
    {

        public override void SetDataValues(DataProvider<MyOtherArgs> dataProvider)
        {
        }

        private Type argsType = typeof(MyOtherArgs);

        protected override MyOtherArgs CreateInstance()
        {
            return new MyOtherArgs();        }
    }

    /// <summary>
    ///  The data definition is available to data providers and are used for initialization.
    /// </summary>
    internal class MyOtherArgsDataDefinition : CommandDataDefinition<MyOtherArgs>
    {

        public MyOtherArgsDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
            : base(parentDataDefinition, rootDataDefinition)
        {
            string fullArgsName = typeof(MyOtherArgs).FullName!;
        }

    }
}
