//HintName: Bar.cs
// <auto-generated />
# nullable enable

using DragonFruit2;
using DragonFruit2.Validators;
using System.CommandLine;
using System.Diagnostics.CodeAnalysis;

namespace MyNamespace
{
    /// <summary>
    /// Auto-generated partial class for building CLI commands for <see cref="Bar"/>" and creating a new Bar instance from a <see cref="System.CommandLine.ParseResult" />.
    /// </summary>
    public partial class Bar : EveningGreetingArgs
    {

        [SetsRequiredMembers()]
        protected Bar(DataValue<int>? ageDataValue, DataValue<string>? nameDataValue)
            : base(ageDataValue, nameDataValue)
        {

            static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)
            {
                return dataValue switch
                {
                    null => false,
                    { IsSet: true } => true,
                    _ => false
                };
            }
        }

        public IEnumerable<Diagnostic> Validate()
        {
            var failures = new List<Diagnostic>();
            InitializeValidators();


            return failures;
        }

        private void InitializeValidators()
        {
        }

        static partial void RegisterCustomDefaults(Builder<MyArgs> builder, DefaultDataProvider<MyArgs> defaultDataProvider);

        public class BarDataValues : DataValues<MyArgs>
        {

            public BarDataValues(BarDataDefinition commandDefinition)
                : base(commandDefinition)
            {
            }

            public override void SetDataValues(DataProvider<MyArgs> dataProvider, Result<MyArgs> result)
            {
                if (Age is not null && !Age.IsSet)
                {
                    dataProvider.TrySetDataValue(Age, result);
                }
                if (Name is not null && !Name.IsSet)
                {
                    dataProvider.TrySetDataValue(Name, result);
                }
            }

            private Type argsType = typeof(Bar);
            public DataValue<int> Age { get; }
            public DataValue<string> Name { get; }

            protected override Bar CreateInstance()
            {
                return new Bar(Age, Name);            }
        }

        /// <summary>
        ///  The data definition is available to data providers and are used for initialization.
        /// </summary>
        public partial class BarDataDefinition : CommandDataDefinition<MyArgs>
        {

            public BarDataDefinition(CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)
                : base(parentDataDefinition, rootDataDefinition)
            {
                GetDataValues = () => new BarDataValues(this);
                RegisterCustomizations();
            }

            public override IEnumerable<TReturn> CreateMembers<TReturn>(ICreatesMembers<TReturn> dataProvider)
            {
                return new List<TReturn>
                {
                };
            }

        }
    }
}
