using DragonFruit2.Generators.Metadata;

namespace DragonFruit2.Generators.CodeOutput;

// The Cli uses a trick base on C# overload resolution behavior. Items in the current namespace have precedence over those in imported namespaces.
// When the user initially creates the app, importing DragonFruit2 supplies a CLI class for IntelliSense. When generation occurs, this call
// is replaced with the generated CLI. This design allows access to the RootCommandBuilder without complicating user code. In modern .NET, this 
// could also be done with a static interface method. However, old .NET Framework...
public class OutputCli
{
    internal static string GetSource(string? entryPointNamespace, IEnumerable<CliInfo> cliInfos)
    {
        var sb = new StringBuilderWrapper();
        FileOpening(sb, entryPointNamespace, cliInfos);
        sb.OpenNamespace(entryPointNamespace);


        OpenClass(sb);
        CreateBuilder(cliInfos, sb);
        ParseArgsMethod(sb);
        TryParseArgsMethod(sb);
        //TryExecute(commandInfo, sb);

        sb.CloseClass();
        sb.CloseNamespace(entryPointNamespace);
        return sb.ToString();
    }

    private static void FileOpening(StringBuilderWrapper sb, string? entryPointNamespace, IEnumerable<CliInfo> cliInfos)
    {
        var commandNamespaces = cliInfos.Select(c=>c.RootTypeNamespace).Distinct();
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;",
                       "using DragonFruit2.Validators;"]);
        // This adds the command namespaces when they are not in the same namespace as the call to
        // `Cli.TryParse`, including top-level statements. This avoids having to qualify sub and parent
        // calls.
        foreach (var commandNamespace in commandNamespaces)
        {
            if (!string.IsNullOrEmpty(commandNamespace) && entryPointNamespace != commandNamespace)
            {
                sb.AppendLine($"using {commandNamespace};");
            }
        }
    }

    internal static void OpenClass(StringBuilderWrapper sb)
    {
        sb.AppendLines([
                "/// <summary>",
                $"""/// Auto-generated partial class that supplies the root CommandBuilder type.""",
                "/// </summary>",
                $"public class Cli"]);
        sb.OpenCurly();
    }

    private static void CreateBuilder(IEnumerable<CliInfo> cliInfos, StringBuilderWrapper sb)
    {

        sb.XmlSummary("Creates a Builder, which can be configured, the System.CommandLine API can be accessed, and which can be reused (especially helpful in testing). ");
        sb.XmlRemarks("The CommandClass specified as the type argument must be public.");
        sb.XmlRemarks("You may need to build after editing this line.");
        sb.XmlRemarks("It is not currently clear how builders and configuration are the same and different and thus expected changes in this space. Accessing it is currently difficult to avoid confusion.");
        sb.XmlTypeParam("TRootCommand", "The type containing the CLI definition, the root command if there are subcommands.");

        sb.OpenMethod($"public static Builder<TRootCommand>? CreateBuilder<TRootCommand>()");

        foreach (var cliInfo in cliInfos)
        {
            var rootName = cliInfo.RootCommandName;
            sb.OpenIf($"typeof(TRootCommand) == typeof({rootName})");
            sb.AppendLine($"var builder = new Builder<{rootName}>(new {rootName}.{rootName}DataDefinition(null, null));");
            sb.AppendLines([$"return builder is Builder<TRootCommand> typedBuilder",
            "      ? typedBuilder",
            "      : throw new InvalidOperationException(\"Type mismatch creating builder.\");"]);
            sb.CloseIf();
        }

        sb.Return("null");
        sb.CloseMethod();
        sb.AppendLine();
    }
    private static void ParseArgsMethod(StringBuilderWrapper sb)
    {
        sb.XmlSummary("Parses CLI arguments to fill the specified CommandClass.<br/>This method is generated specific to the type argument.<br/>You may need to build after editing.");
        sb.XmlRemarks("The CommandClass specified as the type argument must be public.");
        sb.XmlTypeParam("TRootCommand", "The type containing the CLI definition.");
        sb.XmlParam("args", "Optionaly pass the commandline args, using the keyword `args`. If not passed, they will be retrieved for you.");

        sb.OpenMethod($"public static Result<TRootCommand> ParseArgs<TRootCommand>(string[]? args = null)");

        sb.AppendLine("var builder = CreateBuilder<TRootCommand>();");
        sb.OpenIf("builder is null");
        sb.AppendLine($"var result = new Result<TRootCommand>(Builder<TRootCommand>.GetArgsFromEnvironment());");
        sb.AppendLine("result.AddDiagnostic(new Diagnostic(DiagnosticId.CouldNotFindBuilder.ToValidationIdString(), DiagnosticSeverity.Error));");
        sb.Return("result");
        sb.CloseIf();

        sb.AppendLine($"return builder.ParseArgs(args);");

        sb.CloseMethod();
        sb.AppendLine();
    }

    private static void TryParseArgsMethod(StringBuilderWrapper sb)
    {
        sb.XmlSummary("Attempts to parses CLI arguments and fill the specified CommandClass.<br/>This method is generated specific to the type argument.<br/>You may need to build after editing.");
        sb.XmlRemarks("The CommandClass specified as the type argument must be public.");
        sb.XmlTypeParam("TRootCommand", "The type containing the CLI definition.");
        sb.XmlParam("result", "An out parameter that contains an instance of the requested class and supporting data, such as diagnostics, a suggested CLI return value, etc.");
        sb.XmlParam("args", "Optionaly pass the commandline args, using the keyword `args`. If not passed, they will be retrieved for you.");
        sb.XmlException("InvalidOperationException", "To be implemented soon.");

        sb.OpenMethod($"public static bool TryParseArgs<TRootCommand>(out Result<TRootCommand> result, string[]? args = null)");

        sb.AppendLine($"result = ParseArgs<TRootCommand>(args);");
        sb.Return("result.IsValid");
        sb.CloseMethod();
    }

    private static void BuilderFinderFragment(StringBuilderWrapper sb)
        {
        sb.AppendLine("var builder = CreateBuilder<TRootCommand>();");
        sb.OpenIf("builder is null");
        sb.AppendLine($"var result = new Result<TRootCommand>(Builder<TRootCommand>.GetArgsFromEnvironment());");
        sb.AppendLine("result.AddDiagnostic(new Diagnostic(DiagnosticId.CouldNotFindBuilder.ToValidationIdString(), DiagnosticSeverity.Error));");
        sb.Return("result");
        sb.CloseIf();
    }
}

