using DragonFruit2.Generators.Metadata;

namespace DragonFruit2.Generators.CodeOutput;

internal class OutputPartialArgs
{
    internal static string GetSourcePartialArgs(CommandNode commandNode)
    {
        var commandInfo = commandNode.CommandInfo;
        var sb = new StringBuilderWrapper();
        FileOpening(sb);
        sb.OpenNamespace(commandInfo.NamespaceName);

        OpenClass(commandInfo, sb);

        Constructors(sb, commandNode);
        RegisterCustomDefaultsPartialMethod(sb, commandNode);

        OutputDataDefinition.GetClass(sb, commandNode);
        OutputDataValues.GetClass(sb, commandNode);

        sb.CloseClass();
        sb.CloseNamespace(commandInfo.NamespaceName);

        return sb.ToString();
    }

    private static void FileOpening(StringBuilderWrapper sb)
    {
        sb.AppendLines([
                       "// <auto-generated />",
                       "# nullable enable",
                       "",
                       "using DragonFruit2;",
                       "using DragonFruit2.Validators;",
                       "using System.CommandLine;",
                       "using System.Diagnostics.CodeAnalysis;"]);
    }

    internal static void OpenClass(CommandInfo commandInfo, StringBuilderWrapper sb)
    {
        var baseType = commandInfo.BaseTypeName ?? $"CommandRootBase<{commandInfo.Name}>";
        sb.XmlSummary(
                $"""Auto-generated partial class for building CLI commands for <see cref="{commandInfo.Name}"/>" and creating a new {commandInfo.Name} instance from a <see cref="System.CommandLine.ParseResult" />.""");
        // While we know the accessibility, we do not use it hear to improved the user experience if the implementing programmer changes the accessiblity.
        // Un C#, when no accessibiity is declared on a partial class, the accessibility of other portions of the partial are used
        sb.OpenClass($"partial class {commandInfo.Name} : {baseType}");
    }

    private static void Constructors(StringBuilderWrapper sb, CommandNode commandNode)
    {
        var commandInfo = commandNode.CommandInfo;
        // TODO: Can we allow both base setting of properties and respect for a user-created parameterles ctor? Maybe not.
        // TODO: Only generate the following constructor if the user does not create it
        if (commandInfo.GetOptionsAndArguments().Any())
        {
            sb.OpenMethod($"public {commandInfo.Name}()");
            sb.CloseMethod();
        }
        sb.AppendLine();

        sb.Append("[SetsRequiredMembers()]");
        var parameters = string.Join(", ", commandNode.GetSelfAndAncestorPropInfos()
                         .Select(CtorParameter));
        var calledCtor = commandNode.GetAncestorPropInfos().Any()
            ? $"base({string.Join(", ", commandNode.GetAncestorPropInfos()
                        .Select(p => $"{p.Name.ToCamelCase()}DataValue"))})"
            : commandInfo.GetOptionsAndArguments().Any()
                ? "this()"
                : null;
        sb.OpenConstructor($"protected {commandInfo.Name}({string.Join(", ", parameters)})", calledCtor);

        foreach (var propInfo in commandInfo.GetOptionsAndArguments())
        {

            string dataValueName = $"{propInfo.Name.ToCamelCase()}DataValue";
            sb.AppendLine($"""if (ValueIsAvailable({dataValueName})) {propInfo.Name} = {dataValueName}.Value;""");
        }

        if (commandInfo.GetOptionsAndArguments().Any())
        {
            sb.OpenMethod("static bool ValueIsAvailable<T>([NotNullWhen(true)] DataValue<T>? dataValue)");
            sb.Comment("This is generated because it should not be used outside the constructor.");
            sb.AppendLine("return dataValue switch");
            sb.OpenCurly();
            sb.AppendLine("null => false,");
            sb.AppendLine("{ IsSet: true } => true,");
            sb.AppendLine("_ => false");
            sb.CloseCurly(endStatement: true);
            sb.CloseMethod();
        }

        sb.CloseConstructor();

        static string CtorParameter(PropInfo p)
            => $"DataValue<{p.TypeName}> {p.Name.ToCamelCase()}DataValue";
    }

    internal static void ValidateMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    {
        sb.OpenMethod("public IEnumerable<Diagnostic> Validate()");
        sb.AppendLine("var failures = new List<Diagnostic>();");
        sb.AppendLine("InitializeValidators();");
        sb.AppendLine();
        foreach (var prop in commandInfo.GetOptionsAndArguments())
        {
            if (prop.Validators is not null && prop.Validators.Any())
            {
                var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
                sb.OpenIf($"{localSymbolName}Validators is not null");
                sb.OpenForEach($"var validator in {localSymbolName}Validators");
                sb.AppendLine($"""failures.AddRange(validator.Validate({prop.Name}));""");
                sb.CloseForEach();
                sb.CloseIf();
            }
        }
        sb.AppendLine();
        sb.AppendLine("return failures;");
        sb.CloseMethod();
    }

    //internal static void InitializeValidatorsMethod(StringBuilderWrapper sb, CommandInfo commandInfo)
    //{
    //    sb.OpenMethod($"""private void InitializeValidators()""");
    //    foreach (var prop in commandInfo.PropInfos)
    //    {
    //        if (prop.Validators is not null && prop.Validators.Any())
    //        {
    //            var localSymbolName = OutputHelpers.GetLocalSymbolName(prop.Name);
    //            sb.AppendLine($"{localSymbolName}Validators ??= new List<Validator<{prop.TypeName}>>();");
    //            foreach (var validator in prop.Validators)
    //            {
    //                sb.Append($"""{localSymbolName}Validators.Add(new {validator.Name}Validator<{prop.TypeName}>("{prop.Name}", """);
    //                sb.Append(string.Join(", ", validator.ConstructorArguments));
    //                if (validator.NamedArguments.Any())
    //                {
    //                    sb.Append(",");
    //                    sb.Append(string.Join(", ", validator.NamedArguments.Select(kv => $"{kv.Key}: {kv.Value}")));
    //                }
    //                sb.AppendLine("));");
    //            }
    //            sb.AppendLine();
    //        }
    //    }
    //    sb.CloseMethod();
    //}

    internal static void RegisterCustomDefaultsPartialMethod(StringBuilderWrapper sb, CommandNode commandNode)
    {

        sb.AppendLine();
        sb.Append($"static partial void RegisterCustomDefaults(Builder<{commandNode.RootCommandNode?.FullName}> builder, DefaultDataProvider<{commandNode.RootCommandNode?.FullName}> defaultDataProvider);");
        sb.AppendLine();
    }

    //internal static void GetArgsBuilder(StringBuilderWrapper sb, CommandNode commandNode)
    //{
    //    sb.OpenMethod($"public static ArgsBuilder<{commandNode.RootCommandName}> GetArgsBuilder(Builder<{commandNode.RootCommandName}> builder, CommandDataDefinition? parentDataDefinition, CommandDataDefinition? rootDataDefinition)");
    //    sb.AppendLine($"return new {commandNode.RootCommandName}.{commandNode.RootCommandName}ArgsBuilder(parentDataDefinition, rootDataDefinition);");
    //    sb.CloseMethod();
    //}
}
